language: generic
sudo: required
cache:
  bundler: true
  directories:
    - $HOME/docker

services:
  - docker


after_success: |
  bash <(curl -s https://codecov.io/bash)

script:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run spacechop build
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run spacechop npm run build:dry
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up --abort-on-container-exit

before_cache:
  # Save tagged docker images
  - rm $HOME/docker/*.tar.gz
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
